name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: install-laravel-dependencies
        working-directory: ./laravel-api
        run: composer install

      - name: install-react-dependencies
        working-directory: ./react-ui
        run: yarn

      - name: build-react
        working-directory: ./react-ui
        run: yarn deploy
        env:
          PUBLIC_URL: '/public'

      - name: configure-deploy-directory
        run: |
          mkdir deploy
          # deploy laravel as root
          mv laravel-api/* deploy
          # replace to index.php for webserver to detect
          mv deploy/server.php deploy/index.php
          # address htaccess issue
          cp deploy/public/.htaccess deploy
          # rename index.html to blade using web view resource
          mv react-ui/build deploy/client
          mv deploy/client/index.html deploy/resources/views/app.blade.php
          # static file using public url defined by the build steps
          mv deploy/client/* deploy/public

      - name: push-to-special-branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: deploy # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
